line-length = 120
exclude = [
  "compare-results.py",
]

[lint]
ignore = [
  "BLE001",  # https://docs.astral.sh/ruff/rules/blind-except/
  "DTZ001",  # https://docs.astral.sh/ruff/rules/call-datetime-without-tzinfo/
  "DTZ004",  # https://docs.astral.sh/ruff/rules/call-datetime-utcfromtimestamp/
  "DTZ005",  # https://docs.astral.sh/ruff/rules/call-datetime-now-without-tzinfo/
  "DTZ007",  # https://docs.astral.sh/ruff/rules/call-datetime-strptime-without-zone/
  "FURB105", # https://docs.astral.sh/ruff/rules/print-empty-string/
  "I001",    # https://docs.astral.sh/ruff/rules/unsorted-imports/
  "LOG015",  # https://docs.astral.sh/ruff/rules/root-logger-call/
  "PIE808",  # https://docs.astral.sh/ruff/rules/unnecessary-range-start/
  "PLC0206", # https://docs.astral.sh/ruff/rules/dict-index-missing-items/
  "PLW0602", # https://docs.astral.sh/ruff/rules/global-variable-not-assigned/
  "RUF012",  # https://docs.astral.sh/ruff/rules/mutable-class-default/
  "SIM102",  # https://docs.astral.sh/ruff/rules/collapsible-if/
  "SIM103",  # https://docs.astral.sh/ruff/rules/needless-bool/
  "SIM118",  # https://docs.astral.sh/ruff/rules/in-dict-keys/
]
