///////////////////////////////////////////////////////////////////////////////
//
// Copyright Test Competence Center (TCC) ETH 2007
//                                                                           //
// The copyright to the computer  program(s) herein  is the property of TCC. //
// The program(s) may be used and/or copied only with the written permission //
// of TCC or in accordance with  the terms and conditions  stipulated in the //
// agreement/contract under which the program(s) have been supplied          //
///////////////////////////////////////////////////////////////////////////////
//
//  File:               MTP3asp_EncDec.cc
//  Rev:                R11A01
//  Prodnr:             CNL 113 337
//  Updated:            2007-09-17
//  Contact:            http://ttcn.ericsson.se
///////////////////////////////////////////////////////////////////////////////

// Please note: Because the encoder/decoder functions are generated by the 
// TITAN, the MTP3asp_EncDec.cc is kept only for compatibility issue and 
// should be removed from the projects.
