# https://github.com/edgecomllc/eupf/blob/main/docs/Configuration.md
interface_name: [lo]
xdp_attach_mode: generic
api_address: 127.0.0.1:8080
pfcp_address: 127.0.0.1:8805
pfcp_node_id: 127.0.0.1
metrics_address: 127.0.0.1:9090
n3_address: 127.0.0.1
qer_map_size: 1024
far_map_size: 1024
pdr_map_size: 1024
feature_ueip: true
feature_ftup: true
teid_pool: 65535
