name: smdpp
version: 1.0.0
description: Osmocom SM-DP+ TTCN-3 Test Suite
author: Osmocom

sources:
  - "smdpp_Tests.ttcn"
  - "General_Types.ttcn"
  - "IPL4asp_Functions.ttcn"
  - "IPL4asp_PortType.ttcn"
  - "IPL4asp_Types.ttcn"
  - "Misc_Helpers.ttcn"
  - "Native_Functions.ttcn"
  - "Osmocom_Types.ttcn"
  - "PIPEasp_PortType.ttcn"
  - "PIPEasp_Types.ttcn"
  - "PKIX1Explicit88_Templates.ttcn"
  - "PKIX1Explicit88_Types.ttcn"
  - "PKIX1Implicit88_Templates.ttcn"
  - "PKIX1Implicit88_Types.ttcn"
  - "RSPDefinitions_Templates.ttcn"
  - "RSPDefinitions_Types.ttcn"
  - "SGP32Definitions_Templates.ttcn"
  - "SGP32Definitions_Types.ttcn"
  - "Socket_API_Definitions.ttcn"
  - "TCCConversion_Functions.ttcn"
  - "TCCInterface_Functions.ttcn"
  - "es12_Types_JSON.ttcn"
  - "es2p_Types_JSON.ttcn"
  - "es9p_Types_JSON.ttcn"
  - "esx_header_Types_JSON.ttcn"

imports:
  - "PKIX1Explicit88.asn"
  - "PKIX1Implicit88.asn"
  - "PEDefinitions.asn"
  - "RSPDefinitions.asn"
  - "SGP32Definitions.asn"