#pragma once

#include "rsp_ossl.h"
#include <openssl/asn1.h>
#include <openssl/asn1t.h>

/* Basic enumerated types */
ASN1_ITEM_TEMPLATE(REMOTE_OP_ID) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, REMOTE_OP_ID, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(REMOTE_OP_ID)
IMPLEMENT_ASN1_FUNCTIONS(REMOTE_OP_ID)

ASN1_ITEM_TEMPLATE(PROFILE_STATE) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, PROFILE_STATE, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(PROFILE_STATE)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_STATE)

ASN1_ITEM_TEMPLATE(ICON_TYPE) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, ICON_TYPE, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(ICON_TYPE)
IMPLEMENT_ASN1_FUNCTIONS(ICON_TYPE)

ASN1_ITEM_TEMPLATE(PROFILE_CLASS) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, PROFILE_CLASS, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(PROFILE_CLASS)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_CLASS)

ASN1_ITEM_TEMPLATE(DOWNLOAD_ERROR_CODE) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, DOWNLOAD_ERROR_CODE, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(DOWNLOAD_ERROR_CODE)
IMPLEMENT_ASN1_FUNCTIONS(DOWNLOAD_ERROR_CODE)

ASN1_ITEM_TEMPLATE(AUTHENTICATE_ERROR_CODE) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, AUTHENTICATE_ERROR_CODE, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_ERROR_CODE)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_ERROR_CODE)

ASN1_ITEM_TEMPLATE(CANCEL_SESSION_REASON) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, CANCEL_SESSION_REASON, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(CANCEL_SESSION_REASON)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_REASON)

ASN1_ITEM_TEMPLATE(BPP_COMMAND_ID) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, BPP_COMMAND_ID, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(BPP_COMMAND_ID)
IMPLEMENT_ASN1_FUNCTIONS(BPP_COMMAND_ID)

ASN1_ITEM_TEMPLATE(ERROR_REASON) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG, 0, ERROR_REASON, ASN1_INTEGER)
ASN1_ITEM_TEMPLATE_END(ERROR_REASON)
IMPLEMENT_ASN1_FUNCTIONS(ERROR_REASON)

/* Complex structures with SEQUENCE and nested types */

/* RSP_CAPABILITY */
ASN1_SEQUENCE(RSP_CAPABILITY) = {
    ASN1_SIMPLE(RSP_CAPABILITY, flags, ASN1_BIT_STRING)
} ASN1_SEQUENCE_END(RSP_CAPABILITY)
IMPLEMENT_ASN1_FUNCTIONS(RSP_CAPABILITY)

/* CERTIFICATION_DATA_OBJECT */
ASN1_SEQUENCE(CERTIFICATION_DATA_OBJECT) = {
    ASN1_SIMPLE(CERTIFICATION_DATA_OBJECT, platformLabel, ASN1_UTF8STRING),
    ASN1_SIMPLE(CERTIFICATION_DATA_OBJECT, discoveryBaseURL, ASN1_UTF8STRING)
} ASN1_SEQUENCE_END(CERTIFICATION_DATA_OBJECT)
IMPLEMENT_ASN1_FUNCTIONS(CERTIFICATION_DATA_OBJECT)

/* EUICC_INFO1 */
ASN1_SEQUENCE(EUICC_INFO1_INNER) = {
    ASN1_IMP(EUICC_INFO1_INNER, svn, VersionType, 2),
    ASN1_IMP_SEQUENCE_OF(EUICC_INFO1_INNER, euiccCiPKIdListForVerification, ASN1_OCTET_STRING, 9),
    ASN1_IMP_SEQUENCE_OF(EUICC_INFO1_INNER, euiccCiPKIdListForSigning, ASN1_OCTET_STRING, 10)
} ASN1_SEQUENCE_END(EUICC_INFO1_INNER)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_INFO1_INNER)

ASN1_ITEM_TEMPLATE(EUICC_INFO1) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG  | ASN1_TFLG_CONTEXT, 32, EUICC_INFO1, EUICC_INFO1_INNER)
ASN1_ITEM_TEMPLATE_END(EUICC_INFO1)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_INFO1)

/* GET_EUICC_INFO1_REQUEST */
ASN1_SEQUENCE(GET_EUICC_INFO1_REQUEST_INNER) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(GET_EUICC_INFO1_REQUEST_INNER)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_INFO1_REQUEST_INNER)

ASN1_ITEM_TEMPLATE(GET_EUICC_INFO1_REQUEST) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG  | ASN1_TFLG_CONTEXT, 32, GET_EUICC_INFO1_REQUEST, GET_EUICC_INFO1_REQUEST_INNER)
ASN1_ITEM_TEMPLATE_END(GET_EUICC_INFO1_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_INFO1_REQUEST)

/* DEVICE_ADDITIONAL_FEATURE_SUPPORT */
ASN1_SEQUENCE(DEVICE_ADDITIONAL_FEATURE_SUPPORT) = {
    ASN1_OPT(DEVICE_ADDITIONAL_FEATURE_SUPPORT, naiSupport, VersionType)
} ASN1_SEQUENCE_END(DEVICE_ADDITIONAL_FEATURE_SUPPORT)
IMPLEMENT_ASN1_FUNCTIONS(DEVICE_ADDITIONAL_FEATURE_SUPPORT)

/* DEVICE_CAPABILITIES */
ASN1_SEQUENCE(DEVICE_CAPABILITIES) = {
    ASN1_OPT(DEVICE_CAPABILITIES, gsmSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, utranSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, cdma2000onexSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, cdma2000hrpdSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, cdma2000ehrpdSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, eutranEpcSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, contactlessSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, rspCrlSupportedVersion, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, nrEpcSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, nr5gcSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, eutran5gcSupportedRelease, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, lpaSvn, VersionType),
    ASN1_OPT(DEVICE_CAPABILITIES, catSupportedClasses, ASN1_BIT_STRING),
    ASN1_OPT(DEVICE_CAPABILITIES, euiccFormFactorType, ASN1_INTEGER),
    ASN1_OPT(DEVICE_CAPABILITIES, deviceAdditionalFeatureSupport, DEVICE_ADDITIONAL_FEATURE_SUPPORT)
} ASN1_SEQUENCE_END(DEVICE_CAPABILITIES)
IMPLEMENT_ASN1_FUNCTIONS(DEVICE_CAPABILITIES)

/* DEVICE_INFO */
ASN1_SEQUENCE(DEVICE_INFO) = {
    ASN1_SIMPLE(DEVICE_INFO, tac, Octet4),
    ASN1_SIMPLE(DEVICE_INFO, deviceCapabilities, DEVICE_CAPABILITIES),
    ASN1_OPT(DEVICE_INFO, imei, Octet8)
} ASN1_SEQUENCE_END(DEVICE_INFO)
IMPLEMENT_ASN1_FUNCTIONS(DEVICE_INFO)

/* OPERATOR_ID */
ASN1_SEQUENCE(OPERATOR_ID) = {
    ASN1_SIMPLE(OPERATOR_ID, mccMnc, ASN1_OCTET_STRING),
    ASN1_OPT(OPERATOR_ID, gid1, ASN1_OCTET_STRING),
    ASN1_OPT(OPERATOR_ID, gid2, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(OPERATOR_ID)
IMPLEMENT_ASN1_FUNCTIONS(OPERATOR_ID)

/* NOTIFICATION_CONFIGURATION_INFORMATION */
ASN1_SEQUENCE(NOTIFICATION_CONFIGURATION_INFORMATION) = {
    ASN1_SIMPLE(NOTIFICATION_CONFIGURATION_INFORMATION, profileManagementOperation, ASN1_BIT_STRING),
    ASN1_SIMPLE(NOTIFICATION_CONFIGURATION_INFORMATION, notificationAddress, ASN1_UTF8STRING)
} ASN1_SEQUENCE_END(NOTIFICATION_CONFIGURATION_INFORMATION)
IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_CONFIGURATION_INFORMATION)

/* NOTIFICATION_CONFIG_INFO_SEQUENCE */
ASN1_SEQUENCE(NOTIFICATION_CONFIG_INFO_SEQUENCE) = {
    ASN1_SEQUENCE_OF(NOTIFICATION_CONFIG_INFO_SEQUENCE, list, NOTIFICATION_CONFIGURATION_INFORMATION)
} ASN1_SEQUENCE_END(NOTIFICATION_CONFIG_INFO_SEQUENCE)
IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_CONFIG_INFO_SEQUENCE)

/* VENDOR_SPECIFIC_EXTENSION_ELEMENT */
ASN1_SEQUENCE(VENDOR_SPECIFIC_EXTENSION_ELEMENT) = {
    ASN1_EXP(VENDOR_SPECIFIC_EXTENSION_ELEMENT, vendorOid, ASN1_OBJECT, 0),
    ASN1_EXP(VENDOR_SPECIFIC_EXTENSION_ELEMENT, vendorSpecificData, ASN1_ANY, 1)
} ASN1_SEQUENCE_END(VENDOR_SPECIFIC_EXTENSION_ELEMENT)
IMPLEMENT_ASN1_FUNCTIONS(VENDOR_SPECIFIC_EXTENSION_ELEMENT)

/* VENDOR_SPECIFIC_EXTENSION */
ASN1_SEQUENCE(VENDOR_SPECIFIC_EXTENSION) = {
    ASN1_SEQUENCE_OF(VENDOR_SPECIFIC_EXTENSION, elements, VENDOR_SPECIFIC_EXTENSION_ELEMENT)
} ASN1_SEQUENCE_END(VENDOR_SPECIFIC_EXTENSION)
IMPLEMENT_ASN1_FUNCTIONS(VENDOR_SPECIFIC_EXTENSION)

/* DP_PROPRIETARY_DATA */
ASN1_SEQUENCE(DP_PROPRIETARY_DATA) = {
    ASN1_SIMPLE(DP_PROPRIETARY_DATA, dpOid, ASN1_OBJECT)
    /* Additional fields would be added here */
} ASN1_SEQUENCE_END(DP_PROPRIETARY_DATA)
IMPLEMENT_ASN1_FUNCTIONS(DP_PROPRIETARY_DATA)

/* PROFILE_INFO */
ASN1_SEQUENCE(PROFILE_INFO) = {
    ASN1_OPT(PROFILE_INFO, iccid, Iccid),
    ASN1_IMP_OPT(PROFILE_INFO, isdpAid, ASN1_OCTET_STRING, 15),
    ASN1_EXP_OPT(PROFILE_INFO, profileState, PROFILE_STATE, 112),
    ASN1_EXP_OPT(PROFILE_INFO, profileNickname, ASN1_UTF8STRING, 16),
    ASN1_EXP_OPT(PROFILE_INFO, serviceProviderName, ASN1_UTF8STRING, 17),
    ASN1_EXP_OPT(PROFILE_INFO, profileName, ASN1_UTF8STRING, 18),
    ASN1_EXP_OPT(PROFILE_INFO, iconType, ICON_TYPE, 19),
    ASN1_EXP_OPT(PROFILE_INFO, icon, ASN1_OCTET_STRING, 20),
    ASN1_EXP_OPT(PROFILE_INFO, profileClass, PROFILE_CLASS, 21),
    ASN1_EXP_OPT(PROFILE_INFO, notificationConfigurationInfo, NOTIFICATION_CONFIG_INFO_SEQUENCE, 22),
    ASN1_EXP_OPT(PROFILE_INFO, profileOwner, OPERATOR_ID, 23),
    ASN1_EXP_OPT(PROFILE_INFO, dpProprietaryData, DP_PROPRIETARY_DATA, 24),
    ASN1_EXP_OPT(PROFILE_INFO, profilePolicyRules, ASN1_BIT_STRING, 25),
    ASN1_EXP_OPT(PROFILE_INFO, serviceSpecificDataStoredInEuicc, VENDOR_SPECIFIC_EXTENSION, 34)
} ASN1_SEQUENCE_END(PROFILE_INFO)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO)

/* PROFILE_INFO_LIST_ERROR */
ASN1_SEQUENCE(PROFILE_INFO_LIST_ERROR) = {
    ASN1_SIMPLE(PROFILE_INFO_LIST_ERROR, value, ASN1_INTEGER)
} ASN1_SEQUENCE_END(PROFILE_INFO_LIST_ERROR)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_ERROR)

/* PROFILE_INFO_SEQUENCE */
ASN1_SEQUENCE(PROFILE_INFO_SEQUENCE) = {
    ASN1_SEQUENCE_OF(PROFILE_INFO_SEQUENCE, list, PROFILE_INFO)
} ASN1_SEQUENCE_END(PROFILE_INFO_SEQUENCE)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_SEQUENCE)

/* PROFILE_INFO_LIST_RESPONSE */
ASN1_CHOICE(PROFILE_INFO_LIST_RESPONSE) = {
    ASN1_SIMPLE(PROFILE_INFO_LIST_RESPONSE, value.profileInfoListOk, PROFILE_INFO_SEQUENCE),
    ASN1_SIMPLE(PROFILE_INFO_LIST_RESPONSE, value.profileInfoListError, PROFILE_INFO_LIST_ERROR)
} ASN1_CHOICE_END(PROFILE_INFO_LIST_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_RESPONSE)

/* PROFILE_INFO_LIST_SEARCH_CRITERIA */
ASN1_CHOICE(PROFILE_INFO_LIST_SEARCH_CRITERIA) = {
    ASN1_IMP(PROFILE_INFO_LIST_SEARCH_CRITERIA, value.isdpAid, ASN1_OCTET_STRING, 15),
    ASN1_SIMPLE(PROFILE_INFO_LIST_SEARCH_CRITERIA, value.iccid, Iccid),
    ASN1_EXP(PROFILE_INFO_LIST_SEARCH_CRITERIA, value.profileClass, PROFILE_CLASS, 21)
} ASN1_CHOICE_END(PROFILE_INFO_LIST_SEARCH_CRITERIA)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_SEARCH_CRITERIA)

/* PROFILE_INFO_LIST_REQUEST */
ASN1_SEQUENCE(PROFILE_INFO_LIST_REQUEST) = {
    ASN1_EXP_OPT(PROFILE_INFO_LIST_REQUEST, searchCriteria, PROFILE_INFO_LIST_SEARCH_CRITERIA, 0),
    ASN1_IMP_OPT(PROFILE_INFO_LIST_REQUEST, tagList, ASN1_OCTET_STRING, 28)
} ASN1_SEQUENCE_END(PROFILE_INFO_LIST_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_REQUEST)

/* STORE_METADATA_REQUEST */
ASN1_SEQUENCE(STORE_METADATA_REQUEST) = {
    ASN1_SIMPLE(STORE_METADATA_REQUEST, iccid, Iccid),
    ASN1_EXP(STORE_METADATA_REQUEST, serviceProviderName, ASN1_UTF8STRING, 17),
    ASN1_EXP(STORE_METADATA_REQUEST, profileName, ASN1_UTF8STRING, 18),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, iconType, ICON_TYPE, 19),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, icon, ASN1_OCTET_STRING, 20),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, profileClass, PROFILE_CLASS, 21),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, notificationConfigurationInfo, NOTIFICATION_CONFIG_INFO_SEQUENCE, 22),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, profileOwner, OPERATOR_ID, 23),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, profilePolicyRules, ASN1_BIT_STRING, 25),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, serviceSpecificDataStoredInEuicc, VENDOR_SPECIFIC_EXTENSION, 34),
    ASN1_EXP_OPT(STORE_METADATA_REQUEST, serviceSpecificDataNotStoredInEuicc, VENDOR_SPECIFIC_EXTENSION, 35)
} ASN1_SEQUENCE_END(STORE_METADATA_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(STORE_METADATA_REQUEST)

/* UPDATE_METADATA_REQUEST */
ASN1_SEQUENCE(UPDATE_METADATA_REQUEST) = {
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, serviceProviderName, ASN1_UTF8STRING, 17),
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, profileName, ASN1_UTF8STRING, 18),
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, iconType, ICON_TYPE, 19),
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, icon, ASN1_OCTET_STRING, 20),
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, profilePolicyRules, ASN1_BIT_STRING, 25),
    ASN1_EXP_OPT(UPDATE_METADATA_REQUEST, serviceSpecificDataStoredInEuicc, VENDOR_SPECIFIC_EXTENSION, 34)
} ASN1_SEQUENCE_END(UPDATE_METADATA_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(UPDATE_METADATA_REQUEST)

/* SMDP_SIGNED2 */
ASN1_SEQUENCE(SMDP_SIGNED2) = {
    ASN1_IMP(SMDP_SIGNED2, transactionId, ASN1_OCTET_STRING, 0),
    ASN1_SIMPLE(SMDP_SIGNED2, ccRequiredFlag, ASN1_BOOLEAN),
    ASN1_IMP_OPT(SMDP_SIGNED2, bppEuiccOtpk, ASN1_OCTET_STRING, 73 | V_ASN1_APPLICATION)
} ASN1_SEQUENCE_END(SMDP_SIGNED2)
IMPLEMENT_ASN1_FUNCTIONS(SMDP_SIGNED2)

/* PREPARE_DOWNLOAD_REQUEST */
ASN1_SEQUENCE(PREPARE_DOWNLOAD_REQUEST) = {
    ASN1_SIMPLE(PREPARE_DOWNLOAD_REQUEST, smdpSigned2, SMDP_SIGNED2),
    ASN1_IMP(PREPARE_DOWNLOAD_REQUEST, smdpSignature2, ASN1_OCTET_STRING, 55),
    ASN1_OPT(PREPARE_DOWNLOAD_REQUEST, hashCc, Octet32),
    ASN1_SIMPLE(PREPARE_DOWNLOAD_REQUEST, smdpCertificate, X509)
} ASN1_SEQUENCE_END(PREPARE_DOWNLOAD_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_REQUEST)


/* CTX_PARAMS_FOR_COMMON_AUTHENTICATION */
ASN1_SEQUENCE(CTX_PARAMS_FOR_COMMON_AUTHENTICATION) = {
    ASN1_OPT(CTX_PARAMS_FOR_COMMON_AUTHENTICATION, matchingId, ASN1_UTF8STRING),
    ASN1_SIMPLE(CTX_PARAMS_FOR_COMMON_AUTHENTICATION, deviceInfo, DEVICE_INFO)
} ASN1_SEQUENCE_END(CTX_PARAMS_FOR_COMMON_AUTHENTICATION)
IMPLEMENT_ASN1_FUNCTIONS(CTX_PARAMS_FOR_COMMON_AUTHENTICATION)

/* CTX_PARAMS1 */
ASN1_CHOICE(CTX_PARAMS1) = {
    ASN1_SIMPLE(CTX_PARAMS1, value.ctxParamsForCommonAuthentication, CTX_PARAMS_FOR_COMMON_AUTHENTICATION)
} ASN1_CHOICE_END(CTX_PARAMS1)
IMPLEMENT_ASN1_FUNCTIONS(CTX_PARAMS1)

/* SERVER_SIGNED1 */
ASN1_SEQUENCE(SERVER_SIGNED1) = {
    ASN1_IMP(SERVER_SIGNED1, transactionId, TransactionId, 0),
    ASN1_IMP(SERVER_SIGNED1, euiccChallenge, Octet16, 1),
    ASN1_IMP(SERVER_SIGNED1, serverAddress, ASN1_UTF8STRING, 3),
    ASN1_IMP(SERVER_SIGNED1, serverChallenge, Octet16, 4)
} ASN1_SEQUENCE_END(SERVER_SIGNED1)
IMPLEMENT_ASN1_FUNCTIONS(SERVER_SIGNED1)

/* AUTHENTICATE_SERVER_REQUEST */
ASN1_SEQUENCE(AUTHENTICATE_SERVER_REQUEST) = {
    ASN1_SIMPLE(AUTHENTICATE_SERVER_REQUEST, serverSigned1, SERVER_SIGNED1),
    ASN1_IMP(AUTHENTICATE_SERVER_REQUEST, serverSignature1, ASN1_OCTET_STRING, 55),
    ASN1_SIMPLE(AUTHENTICATE_SERVER_REQUEST, euiccCiPKIdToBeUsed, ASN1_OCTET_STRING),
    ASN1_SIMPLE(AUTHENTICATE_SERVER_REQUEST, serverCertificate, X509),
    ASN1_SIMPLE(AUTHENTICATE_SERVER_REQUEST, ctxParams1, CTX_PARAMS1)
} ASN1_SEQUENCE_END(AUTHENTICATE_SERVER_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_SERVER_REQUEST)

/* EUICC_INFO2 - must be after prerequisite types are defined */
ASN1_SEQUENCE(EUICC_INFO2) = {
    ASN1_EXP(EUICC_INFO2, profileVersion, VersionType, 1),
    ASN1_EXP(EUICC_INFO2, svn, VersionType, 2),
    ASN1_EXP(EUICC_INFO2, euiccFirmwareVer, VersionType, 3),
    ASN1_EXP(EUICC_INFO2, extCardResource, ASN1_OCTET_STRING, 4),
    ASN1_EXP(EUICC_INFO2, uiccCapability, ASN1_ANY, 5), /* Placeholder for imported UICC_CAPABILITY */
    ASN1_EXP_OPT(EUICC_INFO2, ts102241Version, VersionType, 6),
    ASN1_EXP_OPT(EUICC_INFO2, globalplatformVersion, VersionType, 7),
    ASN1_EXP(EUICC_INFO2, rspCapability, RSP_CAPABILITY, 8),
    ASN1_EXP_SEQUENCE_OF(EUICC_INFO2, euiccCiPKIdListForVerification, ASN1_OCTET_STRING, 9),
    ASN1_EXP_SEQUENCE_OF(EUICC_INFO2, euiccCiPKIdListForSigning, ASN1_OCTET_STRING, 10),
    ASN1_EXP_OPT(EUICC_INFO2, euiccCategory, ASN1_INTEGER, 11),
    ASN1_EXP_OPT(EUICC_INFO2, forbiddenProfilePolicyRules, ASN1_BIT_STRING, 25),
    ASN1_SIMPLE(EUICC_INFO2, ppVersion, VersionType),
    ASN1_SIMPLE(EUICC_INFO2, sasAcreditationNumber, ASN1_UTF8STRING),
    ASN1_EXP_OPT(EUICC_INFO2, certificationDataObject, CERTIFICATION_DATA_OBJECT, 12),
    ASN1_EXP_OPT(EUICC_INFO2, treProperties, ASN1_BIT_STRING, 13),
    ASN1_EXP_OPT(EUICC_INFO2, treProductReference, ASN1_UTF8STRING, 14),
    ASN1_EXP_SEQUENCE_OF_OPT(EUICC_INFO2, additionalEuiccProfilePackageVersions, VersionType, 15)
} ASN1_SEQUENCE_END(EUICC_INFO2)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_INFO2)

/* GET_EUICC_INFO2_REQUEST */
ASN1_SEQUENCE(GET_EUICC_INFO2_REQUEST) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(GET_EUICC_INFO2_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_INFO2_REQUEST)

/* EUICC_SIGNED1 */
ASN1_SEQUENCE(EUICC_SIGNED1) = {
    ASN1_EXP(EUICC_SIGNED1, transactionId, TransactionId, 0),
    ASN1_EXP(EUICC_SIGNED1, serverAddress, ASN1_UTF8STRING, 3),
    ASN1_EXP(EUICC_SIGNED1, serverChallenge, Octet16, 4),
    ASN1_EXP(EUICC_SIGNED1, euiccInfo2, EUICC_INFO2, 34),
    ASN1_SIMPLE(EUICC_SIGNED1, ctxParams1, CTX_PARAMS1)
} ASN1_SEQUENCE_END(EUICC_SIGNED1)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_SIGNED1)

/* AUTHENTICATE_RESPONSE_OK */
ASN1_SEQUENCE(AUTHENTICATE_RESPONSE_OK) = {
    ASN1_SIMPLE(AUTHENTICATE_RESPONSE_OK, euiccSigned1, EUICC_SIGNED1),
    ASN1_IMP(AUTHENTICATE_RESPONSE_OK, euiccSignature1, ASN1_OCTET_STRING, 55),
    ASN1_SIMPLE(AUTHENTICATE_RESPONSE_OK, euiccCertificate, X509),
    ASN1_SIMPLE(AUTHENTICATE_RESPONSE_OK, eumCertificate, X509)
} ASN1_SEQUENCE_END(AUTHENTICATE_RESPONSE_OK)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_RESPONSE_OK)

/* AUTHENTICATE_RESPONSE_ERROR */
ASN1_SEQUENCE(AUTHENTICATE_RESPONSE_ERROR) = {
    ASN1_EXP(AUTHENTICATE_RESPONSE_ERROR, transactionId, TransactionId, 0),
    ASN1_SIMPLE(AUTHENTICATE_RESPONSE_ERROR, authenticateErrorCode, AUTHENTICATE_ERROR_CODE)
} ASN1_SEQUENCE_END(AUTHENTICATE_RESPONSE_ERROR)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_RESPONSE_ERROR)

/* AUTHENTICATE_SERVER_RESPONSE */
ASN1_CHOICE(AUTHENTICATE_SERVER_RESPONSE) = {
    ASN1_SIMPLE(AUTHENTICATE_SERVER_RESPONSE, value.authenticateResponseOk, AUTHENTICATE_RESPONSE_OK),
    ASN1_SIMPLE(AUTHENTICATE_SERVER_RESPONSE, value.authenticateResponseError, AUTHENTICATE_RESPONSE_ERROR)
} ASN1_CHOICE_END(AUTHENTICATE_SERVER_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_SERVER_RESPONSE)

/* CANCEL_SESSION_REQUEST */
ASN1_SEQUENCE(CANCEL_SESSION_REQUEST) = {
    ASN1_SIMPLE(CANCEL_SESSION_REQUEST, transactionId, TransactionId),
    ASN1_SIMPLE(CANCEL_SESSION_REQUEST, reason, CANCEL_SESSION_REASON)
} ASN1_SEQUENCE_END(CANCEL_SESSION_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_REQUEST)

/* EUICC_CANCEL_SESSION_SIGNED */
ASN1_SEQUENCE(EUICC_CANCEL_SESSION_SIGNED) = {
    ASN1_SIMPLE(EUICC_CANCEL_SESSION_SIGNED, transactionId, TransactionId),
    ASN1_SIMPLE(EUICC_CANCEL_SESSION_SIGNED, smdpOid, ASN1_OBJECT),
    ASN1_SIMPLE(EUICC_CANCEL_SESSION_SIGNED, reason, CANCEL_SESSION_REASON)
} ASN1_SEQUENCE_END(EUICC_CANCEL_SESSION_SIGNED)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_CANCEL_SESSION_SIGNED)

/* CANCEL_SESSION_RESPONSE_OK */
ASN1_SEQUENCE(CANCEL_SESSION_RESPONSE_OK) = {
    ASN1_SIMPLE(CANCEL_SESSION_RESPONSE_OK, euiccCancelSessionSigned, EUICC_CANCEL_SESSION_SIGNED),
    ASN1_IMP(CANCEL_SESSION_RESPONSE_OK, euiccCancelSessionSignature, ASN1_OCTET_STRING, 55)
} ASN1_SEQUENCE_END(CANCEL_SESSION_RESPONSE_OK)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_RESPONSE_OK)

/* CANCEL_SESSION_RESPONSE */
ASN1_CHOICE(CANCEL_SESSION_RESPONSE) = {
    ASN1_SIMPLE(CANCEL_SESSION_RESPONSE, value.cancelSessionResponseOk, CANCEL_SESSION_RESPONSE_OK),
    ASN1_SIMPLE(CANCEL_SESSION_RESPONSE, value.cancelSessionResponseError, ASN1_INTEGER)
} ASN1_CHOICE_END(CANCEL_SESSION_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_RESPONSE)

/* INITIALISE_SECURE_CHANNEL_REQUEST */
ASN1_SEQUENCE(INITIALISE_SECURE_CHANNEL_REQUEST) = {
    ASN1_SIMPLE(INITIALISE_SECURE_CHANNEL_REQUEST, remoteOpId, REMOTE_OP_ID),
    ASN1_EXP(INITIALISE_SECURE_CHANNEL_REQUEST, transactionId, TransactionId, 0),
    ASN1_IMP(INITIALISE_SECURE_CHANNEL_REQUEST, controlRefTemplate, CONTROL_REF_TEMPLATE, 6),
    ASN1_IMP(INITIALISE_SECURE_CHANNEL_REQUEST, smdpOtpk, ASN1_OCTET_STRING, 73),
    ASN1_IMP(INITIALISE_SECURE_CHANNEL_REQUEST, smdpSign, ASN1_OCTET_STRING, 55)
} ASN1_SEQUENCE_END(INITIALISE_SECURE_CHANNEL_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(INITIALISE_SECURE_CHANNEL_REQUEST)


/* BOUND_PROFILE_PACKAGE */
ASN1_SEQUENCE(BOUND_PROFILE_PACKAGE) = {
    ASN1_EXP(BOUND_PROFILE_PACKAGE, initialiseSecureChannelRequest, INITIALISE_SECURE_CHANNEL_REQUEST, 35),
    ASN1_EXP_SEQUENCE_OF(BOUND_PROFILE_PACKAGE, firstSequenceOf87, ASN1_OCTET_STRING, 0),
    ASN1_EXP_SEQUENCE_OF(BOUND_PROFILE_PACKAGE, sequenceOf88, ASN1_OCTET_STRING, 1),
    ASN1_EXP_SEQUENCE_OF_OPT(BOUND_PROFILE_PACKAGE, secondSequenceOf87, ASN1_OCTET_STRING, 2),
    ASN1_EXP_SEQUENCE_OF(BOUND_PROFILE_PACKAGE, sequenceOf86, ASN1_OCTET_STRING, 3)
} ASN1_SEQUENCE_END(BOUND_PROFILE_PACKAGE)
IMPLEMENT_ASN1_FUNCTIONS(BOUND_PROFILE_PACKAGE)

/* GET_EUICC_CHALLENGE_REQUEST */
ASN1_SEQUENCE(GET_EUICC_CHALLENGE_REQUEST) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(GET_EUICC_CHALLENGE_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_CHALLENGE_REQUEST)

/* GET_EUICC_CHALLENGE_RESPONSE */
ASN1_SEQUENCE(GET_EUICC_CHALLENGE_RESPONSE) = {
    ASN1_SIMPLE(GET_EUICC_CHALLENGE_RESPONSE, euiccChallenge, Octet16)
} ASN1_SEQUENCE_END(GET_EUICC_CHALLENGE_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_CHALLENGE_RESPONSE)

/* SUCCESS_RESULT */
ASN1_SEQUENCE(SUCCESS_RESULT) = {
    ASN1_IMP(SUCCESS_RESULT, aid, ASN1_OCTET_STRING, 15),
    ASN1_SIMPLE(SUCCESS_RESULT, simaResponse, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(SUCCESS_RESULT)
IMPLEMENT_ASN1_FUNCTIONS(SUCCESS_RESULT)

/* ERROR_RESULT */
ASN1_SEQUENCE(ERROR_RESULT) = {
    ASN1_SIMPLE(ERROR_RESULT, bppCommandId, BPP_COMMAND_ID),
    ASN1_SIMPLE(ERROR_RESULT, errorReason, ERROR_REASON),
    ASN1_OPT(ERROR_RESULT, simaResponse, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(ERROR_RESULT)
IMPLEMENT_ASN1_FUNCTIONS(ERROR_RESULT)

/* NOTIFICATION_METADATA */
ASN1_SEQUENCE(NOTIFICATION_METADATA) = {
    ASN1_EXP(NOTIFICATION_METADATA, seqNumber, ASN1_INTEGER, 0),
    ASN1_EXP(NOTIFICATION_METADATA, profileManagementOperation, ASN1_BIT_STRING, 1),
    ASN1_SIMPLE(NOTIFICATION_METADATA, notificationAddress, ASN1_UTF8STRING),
    ASN1_OPT(NOTIFICATION_METADATA, iccid, Iccid)
} ASN1_SEQUENCE_END(NOTIFICATION_METADATA)
IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_METADATA)

ASN1_CHOICE(FINAL_RESULT) = {
    ASN1_SIMPLE(FINAL_RESULT, value.successResult, SUCCESS_RESULT),
    ASN1_SIMPLE(FINAL_RESULT, value.errorResult, ERROR_RESULT)
} ASN1_CHOICE_END(FINAL_RESULT)
IMPLEMENT_ASN1_FUNCTIONS(FINAL_RESULT)

ASN1_SEQUENCE(PROFILE_INSTALLATION_RESULT_DATA) = {
    ASN1_EXP(PROFILE_INSTALLATION_RESULT_DATA, transactionId, TransactionId, 0),
    ASN1_EXP(PROFILE_INSTALLATION_RESULT_DATA, notificationMetadata, NOTIFICATION_METADATA, 47),
    ASN1_SIMPLE(PROFILE_INSTALLATION_RESULT_DATA, smdpOid, ASN1_OBJECT),
    ASN1_EXP(PROFILE_INSTALLATION_RESULT_DATA, finalResult, FINAL_RESULT, 2)
} ASN1_SEQUENCE_END(PROFILE_INSTALLATION_RESULT_DATA)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INSTALLATION_RESULT_DATA)


/* Finally define PROFILE_INSTALLATION_RESULT */
ASN1_SEQUENCE(PROFILE_INSTALLATION_RESULT) = {
    ASN1_EXP(PROFILE_INSTALLATION_RESULT, profileInstallationResultData, PROFILE_INSTALLATION_RESULT_DATA, 39),
    ASN1_IMP(PROFILE_INSTALLATION_RESULT, euiccSignPIR, ASN1_OCTET_STRING, 55)
} ASN1_SEQUENCE_END(PROFILE_INSTALLATION_RESULT)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INSTALLATION_RESULT)

/* LIST_NOTIFICATION_REQUEST */
ASN1_SEQUENCE(LIST_NOTIFICATION_REQUEST) = {
    ASN1_EXP_OPT(LIST_NOTIFICATION_REQUEST, profileManagementOperation, ASN1_BIT_STRING, 1)
} ASN1_SEQUENCE_END(LIST_NOTIFICATION_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(LIST_NOTIFICATION_REQUEST)

/* LIST_NOTIFICATION_RESPONSE */
ASN1_CHOICE(LIST_NOTIFICATION_RESPONSE) = {
    ASN1_SEQUENCE_OF(LIST_NOTIFICATION_RESPONSE, value.notificationMetadataList, NOTIFICATION_METADATA),
    ASN1_SIMPLE(LIST_NOTIFICATION_RESPONSE, value.listNotificationsResultError, ASN1_INTEGER)
} ASN1_CHOICE_END(LIST_NOTIFICATION_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(LIST_NOTIFICATION_RESPONSE)

/* SET_NICKNAME_REQUEST */
ASN1_SEQUENCE(SET_NICKNAME_REQUEST) = {
    ASN1_SIMPLE(SET_NICKNAME_REQUEST, iccid, Iccid),
    ASN1_EXP(SET_NICKNAME_REQUEST, profileNickname, ASN1_UTF8STRING, 16)
} ASN1_SEQUENCE_END(SET_NICKNAME_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(SET_NICKNAME_REQUEST)

/* SET_NICKNAME_RESPONSE */
ASN1_SEQUENCE(SET_NICKNAME_RESPONSE) = {
    ASN1_SIMPLE(SET_NICKNAME_RESPONSE, setNicknameResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(SET_NICKNAME_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(SET_NICKNAME_RESPONSE)

/* CONTROL_REF_TEMPLATE */
ASN1_SEQUENCE(CONTROL_REF_TEMPLATE) = {
    ASN1_EXP(CONTROL_REF_TEMPLATE, keyType, Octet1, 0),
    ASN1_EXP(CONTROL_REF_TEMPLATE, keyLen, Octet1, 1),
    ASN1_EXP(CONTROL_REF_TEMPLATE, hostId, OctetTo16, 4)
} ASN1_SEQUENCE_END(CONTROL_REF_TEMPLATE)
IMPLEMENT_ASN1_FUNCTIONS(CONTROL_REF_TEMPLATE)


/* CONFIGURE_ISDP_REQUEST */
ASN1_SEQUENCE(CONFIGURE_ISDP_REQUEST) = {
    ASN1_EXP_OPT(CONFIGURE_ISDP_REQUEST, dpProprietaryData, DP_PROPRIETARY_DATA, 24)
} ASN1_SEQUENCE_END(CONFIGURE_ISDP_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(CONFIGURE_ISDP_REQUEST)

/* REPLACE_SESSION_KEYS_REQUEST */
ASN1_SEQUENCE(REPLACE_SESSION_KEYS_REQUEST) = {
    ASN1_SIMPLE(REPLACE_SESSION_KEYS_REQUEST, initialMacChainingValue, ASN1_OCTET_STRING),
    ASN1_SIMPLE(REPLACE_SESSION_KEYS_REQUEST, ppkEnc, ASN1_OCTET_STRING),
    ASN1_SIMPLE(REPLACE_SESSION_KEYS_REQUEST, ppkCmac, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(REPLACE_SESSION_KEYS_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(REPLACE_SESSION_KEYS_REQUEST)


/* OTHER_SIGNED_NOTIFICATION */
ASN1_SEQUENCE(OTHER_SIGNED_NOTIFICATION) = {
    ASN1_SIMPLE(OTHER_SIGNED_NOTIFICATION, tbsOtherNotification, NOTIFICATION_METADATA),
    ASN1_IMP(OTHER_SIGNED_NOTIFICATION, euiccNotificationSignature, ASN1_OCTET_STRING, 55),
    ASN1_SIMPLE(OTHER_SIGNED_NOTIFICATION, euiccCertificate, X509),
    ASN1_SIMPLE(OTHER_SIGNED_NOTIFICATION, eumCertificate, X509)
} ASN1_SEQUENCE_END(OTHER_SIGNED_NOTIFICATION)
IMPLEMENT_ASN1_FUNCTIONS(OTHER_SIGNED_NOTIFICATION)

/* PENDING_NOTIFICATION */
ASN1_CHOICE(PENDING_NOTIFICATION) = {
    ASN1_EXP(PENDING_NOTIFICATION, value.profileInstallationResult, PROFILE_INSTALLATION_RESULT, 55),
    ASN1_SIMPLE(PENDING_NOTIFICATION, value.otherSignedNotification, OTHER_SIGNED_NOTIFICATION)
} ASN1_CHOICE_END(PENDING_NOTIFICATION)
IMPLEMENT_ASN1_FUNCTIONS(PENDING_NOTIFICATION)

// /* RETRIEVE_NOTIFICATIONS_LIST_RESPONSE */
// ASN1_CHOICE(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE) = {
//     ASN1_SEQUENCE_OF(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE, value.notificationList, PENDING_NOTIFICATION),
//     ASN1_SIMPLE(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE, value.notificationsListResultError, ASN1_INTEGER)
// } ASN1_CHOICE_END(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE)
// IMPLEMENT_ASN1_FUNCTIONS(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE)

/* NOTIFICATION_SENT_REQUEST */
ASN1_SEQUENCE(NOTIFICATION_SENT_REQUEST) = {
    ASN1_EXP(NOTIFICATION_SENT_REQUEST, seqNumber, ASN1_INTEGER, 0)
} ASN1_SEQUENCE_END(NOTIFICATION_SENT_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_SENT_REQUEST)

/* NOTIFICATION_SENT_RESPONSE */
ASN1_SEQUENCE(NOTIFICATION_SENT_RESPONSE) = {
    ASN1_SIMPLE(NOTIFICATION_SENT_RESPONSE, deleteNotificationStatus, ASN1_INTEGER)
} ASN1_SEQUENCE_END(NOTIFICATION_SENT_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_SENT_RESPONSE)


/* ENABLE_PROFILE_RESPONSE */
ASN1_SEQUENCE(ENABLE_PROFILE_RESPONSE) = {
    ASN1_SIMPLE(ENABLE_PROFILE_RESPONSE, enableResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(ENABLE_PROFILE_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(ENABLE_PROFILE_RESPONSE)


/* DISABLE_PROFILE_RESPONSE */
ASN1_SEQUENCE(DISABLE_PROFILE_RESPONSE) = {
    ASN1_SIMPLE(DISABLE_PROFILE_RESPONSE, disableResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(DISABLE_PROFILE_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(DISABLE_PROFILE_RESPONSE)

/* DELETE_PROFILE_REQUEST */
ASN1_CHOICE(DELETE_PROFILE_REQUEST) = {
    ASN1_IMP(DELETE_PROFILE_REQUEST, value.isdpAid, ASN1_OCTET_STRING, 15),
    ASN1_SIMPLE(DELETE_PROFILE_REQUEST, value.iccid, Iccid)
} ASN1_CHOICE_END(DELETE_PROFILE_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(DELETE_PROFILE_REQUEST)

/* DELETE_PROFILE_RESPONSE */
ASN1_SEQUENCE(DELETE_PROFILE_RESPONSE) = {
    ASN1_SIMPLE(DELETE_PROFILE_RESPONSE, deleteResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(DELETE_PROFILE_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(DELETE_PROFILE_RESPONSE)

/* EUICC_MEMORY_RESET_REQUEST */
ASN1_SEQUENCE(EUICC_MEMORY_RESET_REQUEST) = {
    ASN1_EXP(EUICC_MEMORY_RESET_REQUEST, resetOptions, ASN1_BIT_STRING, 2)
} ASN1_SEQUENCE_END(EUICC_MEMORY_RESET_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_MEMORY_RESET_REQUEST)

/* EUICC_MEMORY_RESET_RESPONSE */
ASN1_SEQUENCE(EUICC_MEMORY_RESET_RESPONSE) = {
    ASN1_SIMPLE(EUICC_MEMORY_RESET_RESPONSE, resetResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(EUICC_MEMORY_RESET_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_MEMORY_RESET_RESPONSE)

/* GET_EUICC_DATA_REQUEST */
ASN1_SEQUENCE(GET_EUICC_DATA_REQUEST) = {
    ASN1_IMP(GET_EUICC_DATA_REQUEST, tagList, Octet1, 28)
} ASN1_SEQUENCE_END(GET_EUICC_DATA_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_DATA_REQUEST)

/* GET_EUICC_DATA_RESPONSE */
ASN1_SEQUENCE(GET_EUICC_DATA_RESPONSE) = {
    ASN1_IMP(GET_EUICC_DATA_RESPONSE, eidValue, Octet16, 26)
} ASN1_SEQUENCE_END(GET_EUICC_DATA_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_DATA_RESPONSE)

/* PROFILE_POLICY_AUTHORISATION_RULE */
ASN1_SEQUENCE(PROFILE_POLICY_AUTHORISATION_RULE) = {
    ASN1_SIMPLE(PROFILE_POLICY_AUTHORISATION_RULE, pprIds, ASN1_BIT_STRING),
    ASN1_SEQUENCE_OF(PROFILE_POLICY_AUTHORISATION_RULE, allowedOperators, OPERATOR_ID),
    ASN1_SIMPLE(PROFILE_POLICY_AUTHORISATION_RULE, pprFlags, ASN1_BIT_STRING)
} ASN1_SEQUENCE_END(PROFILE_POLICY_AUTHORISATION_RULE)
IMPLEMENT_ASN1_FUNCTIONS(PROFILE_POLICY_AUTHORISATION_RULE)

/* RULES_AUTHORISATION_TABLE */
ASN1_SEQUENCE(RULES_AUTHORISATION_TABLE) = {
    ASN1_SEQUENCE_OF(RULES_AUTHORISATION_TABLE, rules, PROFILE_POLICY_AUTHORISATION_RULE)
} ASN1_SEQUENCE_END(RULES_AUTHORISATION_TABLE)
IMPLEMENT_ASN1_FUNCTIONS(RULES_AUTHORISATION_TABLE)

/* GET_RAT_REQUEST */
ASN1_SEQUENCE(GET_RAT_REQUEST) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(GET_RAT_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_RAT_REQUEST)

/* GET_RAT_RESPONSE */
ASN1_SEQUENCE(GET_RAT_RESPONSE) = {
    ASN1_SIMPLE(GET_RAT_RESPONSE, rat, RULES_AUTHORISATION_TABLE)
} ASN1_SEQUENCE_END(GET_RAT_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(GET_RAT_RESPONSE)

/* SEGMENTED_CRL_LIST */
ASN1_SEQUENCE(SEGMENTED_CRL_LIST) = {
    ASN1_SEQUENCE_OF(SEGMENTED_CRL_LIST, list, X509_CRL)
} ASN1_SEQUENCE_END(SEGMENTED_CRL_LIST)
IMPLEMENT_ASN1_FUNCTIONS(SEGMENTED_CRL_LIST)

/* LOAD_CRL_REQUEST */
ASN1_SEQUENCE(LOAD_CRL_REQUEST) = {
    ASN1_SIMPLE(LOAD_CRL_REQUEST, crl, X509_CRL)
} ASN1_SEQUENCE_END(LOAD_CRL_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(LOAD_CRL_REQUEST)

/* LOAD_CRL_RESPONSE_OK */
ASN1_SEQUENCE(LOAD_CRL_RESPONSE_OK) = {
    ASN1_SEQUENCE_OF_OPT(LOAD_CRL_RESPONSE_OK, missingParts, ASN1_INTEGER)
} ASN1_SEQUENCE_END(LOAD_CRL_RESPONSE_OK)
IMPLEMENT_ASN1_FUNCTIONS(LOAD_CRL_RESPONSE_OK)

/* LOAD_CRL_RESPONSE */
ASN1_CHOICE(LOAD_CRL_RESPONSE) = {
    ASN1_SIMPLE(LOAD_CRL_RESPONSE, value.loadCRLResponseOk, LOAD_CRL_RESPONSE_OK),
    ASN1_SIMPLE(LOAD_CRL_RESPONSE, value.loadCRLResponseError, ASN1_INTEGER)
} ASN1_CHOICE_END(LOAD_CRL_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(LOAD_CRL_RESPONSE)

/* INITIATE_AUTHENTICATION_REQUEST */
ASN1_SEQUENCE(INITIATE_AUTHENTICATION_REQUEST) = {
    ASN1_EXP(INITIATE_AUTHENTICATION_REQUEST, euiccChallenge, Octet16, 1),
    ASN1_EXP(INITIATE_AUTHENTICATION_REQUEST, smdpAddress, ASN1_UTF8STRING, 3),
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_REQUEST, euiccInfo1, EUICC_INFO1)
} ASN1_SEQUENCE_END(INITIATE_AUTHENTICATION_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(INITIATE_AUTHENTICATION_REQUEST)

/* INITIATE_AUTHENTICATION_OK_ES9 */
ASN1_SEQUENCE(INITIATE_AUTHENTICATION_OK_ES9) = {
    ASN1_EXP(INITIATE_AUTHENTICATION_OK_ES9, transactionId, TransactionId, 0),
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_OK_ES9, serverSigned1, SERVER_SIGNED1),
    ASN1_IMP(INITIATE_AUTHENTICATION_OK_ES9, serverSignature1, ASN1_OCTET_STRING, 55),
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_OK_ES9, euiccCiPKIdToBeUsed, ASN1_OCTET_STRING),
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_OK_ES9, serverCertificate, X509)
} ASN1_SEQUENCE_END(INITIATE_AUTHENTICATION_OK_ES9)
IMPLEMENT_ASN1_FUNCTIONS(INITIATE_AUTHENTICATION_OK_ES9)

/* INITIATE_AUTHENTICATION_RESPONSE */
ASN1_CHOICE(INITIATE_AUTHENTICATION_RESPONSE) = {
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_RESPONSE, value.initiateAuthenticationOk, INITIATE_AUTHENTICATION_OK_ES9),
    ASN1_SIMPLE(INITIATE_AUTHENTICATION_RESPONSE, value.initiateAuthenticationError, ASN1_INTEGER)
} ASN1_CHOICE_END(INITIATE_AUTHENTICATION_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(INITIATE_AUTHENTICATION_RESPONSE)

/* AUTHENTICATE_CLIENT_REQUEST */
ASN1_SEQUENCE(AUTHENTICATE_CLIENT_REQUEST) = {
    ASN1_EXP(AUTHENTICATE_CLIENT_REQUEST, transactionId, TransactionId, 0),
    ASN1_EXP(AUTHENTICATE_CLIENT_REQUEST, authenticateServerResponse, AUTHENTICATE_SERVER_RESPONSE, 56)
} ASN1_SEQUENCE_END(AUTHENTICATE_CLIENT_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_REQUEST)

/* AUTHENTICATE_CLIENT_OK */
ASN1_SEQUENCE(AUTHENTICATE_CLIENT_OK) = {
    ASN1_EXP(AUTHENTICATE_CLIENT_OK, transactionId, TransactionId, 0),
    ASN1_EXP(AUTHENTICATE_CLIENT_OK, profileMetaData, STORE_METADATA_REQUEST, 37),
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_OK, smdpSigned2, SMDP_SIGNED2),
    ASN1_IMP(AUTHENTICATE_CLIENT_OK, smdpSignature2, ASN1_OCTET_STRING, 55),
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_OK, smdpCertificate, X509)
} ASN1_SEQUENCE_END(AUTHENTICATE_CLIENT_OK)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_OK)

/* AUTHENTICATE_CLIENT_RESPONSE_ES9 */
ASN1_CHOICE(AUTHENTICATE_CLIENT_RESPONSE_ES9) = {
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_RESPONSE_ES9, value.authenticateClientOk, AUTHENTICATE_CLIENT_OK),
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_RESPONSE_ES9, value.authenticateClientError, ASN1_INTEGER)
} ASN1_CHOICE_END(AUTHENTICATE_CLIENT_RESPONSE_ES9)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_RESPONSE_ES9)



/* EUICCSigned2 implementation */
ASN1_SEQUENCE(EUICC_SIGNED2) = {
    ASN1_IMP(EUICC_SIGNED2, transactionId, TransactionId, 0),
    ASN1_IMP(EUICC_SIGNED2, euiccOtpk, ASN1_OCTET_STRING, 73),  /* APPLICATION tag */
    ASN1_OPT(EUICC_SIGNED2, hashCc, ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(EUICC_SIGNED2)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_SIGNED2)

/* PrepareDownloadResponseOk implementation */
ASN1_SEQUENCE(PREPARE_DOWNLOAD_RESPONSE_OK) = {
    ASN1_SIMPLE(PREPARE_DOWNLOAD_RESPONSE_OK, euiccSigned2, EUICC_SIGNED2),
    ASN1_IMP(PREPARE_DOWNLOAD_RESPONSE_OK, euiccSignature2, ASN1_OCTET_STRING, 55)  /* APPLICATION tag */
} ASN1_SEQUENCE_END(PREPARE_DOWNLOAD_RESPONSE_OK)
IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE_OK)

/* PrepareDownloadResponseError implementation */
ASN1_SEQUENCE(PREPARE_DOWNLOAD_RESPONSE_ERROR) = {
    ASN1_IMP(PREPARE_DOWNLOAD_RESPONSE_ERROR, transactionId, TransactionId, 0),
    ASN1_SIMPLE(PREPARE_DOWNLOAD_RESPONSE_ERROR, downloadErrorCode, ASN1_INTEGER)
} ASN1_SEQUENCE_END(PREPARE_DOWNLOAD_RESPONSE_ERROR)
IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE_ERROR)


ASN1_CHOICE(PREPARE_DOWNLOAD_RESPONSE_CHOICE) = {
    ASN1_SIMPLE(PREPARE_DOWNLOAD_RESPONSE_CHOICE, d.downloadResponseOk, PREPARE_DOWNLOAD_RESPONSE_OK),
    ASN1_SIMPLE(PREPARE_DOWNLOAD_RESPONSE_CHOICE, d.downloadResponseError, PREPARE_DOWNLOAD_RESPONSE_ERROR)
} ASN1_CHOICE_END(PREPARE_DOWNLOAD_RESPONSE_CHOICE)
IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE_CHOICE)

/* Now apply the [33] tag using ASN1_EX_TEMPLATE_TYPE with EXPLICIT tagging */
typedef PREPARE_DOWNLOAD_RESPONSE_CHOICE PREPARE_DOWNLOAD_RESPONSE;
DECLARE_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE)

ASN1_ITEM_TEMPLATE(PREPARE_DOWNLOAD_RESPONSE) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_EXPTAG | ASN1_TFLG_CONTEXT, 33,
                         PREPARE_DOWNLOAD_RESPONSE, PREPARE_DOWNLOAD_RESPONSE_CHOICE)
ASN1_ITEM_TEMPLATE_END(PREPARE_DOWNLOAD_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE)



/* GetBoundProfilePackageRequest inner implementation */
ASN1_SEQUENCE(GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER) = {
    ASN1_IMP(GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER, transactionId, TransactionId, 0),
    ASN1_SIMPLE(GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER, prepareDownloadResponse, PREPARE_DOWNLOAD_RESPONSE)
} ASN1_SEQUENCE_END(GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER)
IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER)

/* GetBoundProfilePackageRequest with [58] tag */
typedef GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER GET_BOUND_PROFILE_PACKAGE_REQUEST;
DECLARE_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_REQUEST)

ASN1_ITEM_TEMPLATE(GET_BOUND_PROFILE_PACKAGE_REQUEST) =
    ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 58, GET_BOUND_PROFILE_PACKAGE_REQUEST, GET_BOUND_PROFILE_PACKAGE_REQUEST_INNER)
ASN1_ITEM_TEMPLATE_END(GET_BOUND_PROFILE_PACKAGE_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_REQUEST)



/* GET_BOUND_PROFILE_PACKAGE_RESPONSE */
ASN1_CHOICE(GET_BOUND_PROFILE_PACKAGE_RESPONSE) = {
    ASN1_SIMPLE(GET_BOUND_PROFILE_PACKAGE_RESPONSE, value.getBoundProfilePackageOk, GET_BOUND_PROFILE_PACKAGE_OK),
    ASN1_SIMPLE(GET_BOUND_PROFILE_PACKAGE_RESPONSE, value.getBoundProfilePackageError, ASN1_INTEGER)
} ASN1_CHOICE_END(GET_BOUND_PROFILE_PACKAGE_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_RESPONSE)

/* GET_BOUND_PROFILE_PACKAGE_OK */
ASN1_SEQUENCE(GET_BOUND_PROFILE_PACKAGE_OK) = {
    ASN1_EXP(GET_BOUND_PROFILE_PACKAGE_OK, transactionId, TransactionId, 0),
    ASN1_EXP(GET_BOUND_PROFILE_PACKAGE_OK, boundProfilePackage, BOUND_PROFILE_PACKAGE, 54)
} ASN1_SEQUENCE_END(GET_BOUND_PROFILE_PACKAGE_OK)
IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_OK)

/* HANDLE_NOTIFICATION */
ASN1_SEQUENCE(HANDLE_NOTIFICATION) = {
    ASN1_SIMPLE(HANDLE_NOTIFICATION, pendingNotification, PENDING_NOTIFICATION)
} ASN1_SEQUENCE_END(HANDLE_NOTIFICATION)
IMPLEMENT_ASN1_FUNCTIONS(HANDLE_NOTIFICATION)

/* CANCEL_SESSION_REQUEST_ES9 */
ASN1_SEQUENCE(CANCEL_SESSION_REQUEST_ES9) = {
    ASN1_SIMPLE(CANCEL_SESSION_REQUEST_ES9, transactionId, TransactionId),
    ASN1_SIMPLE(CANCEL_SESSION_REQUEST_ES9, cancelSessionResponse, CANCEL_SESSION_RESPONSE)
} ASN1_SEQUENCE_END(CANCEL_SESSION_REQUEST_ES9)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_REQUEST_ES9)

/* CANCEL_SESSION_OK */
ASN1_SEQUENCE(CANCEL_SESSION_OK) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(CANCEL_SESSION_OK)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_OK)

/* CANCEL_SESSION_RESPONSE_ES9 */
ASN1_CHOICE(CANCEL_SESSION_RESPONSE_ES9) = {
    ASN1_SIMPLE(CANCEL_SESSION_RESPONSE_ES9, value.cancelSessionOk, CANCEL_SESSION_OK),
    ASN1_SIMPLE(CANCEL_SESSION_RESPONSE_ES9, value.cancelSessionError, ASN1_INTEGER)
} ASN1_CHOICE_END(CANCEL_SESSION_RESPONSE_ES9)
IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_RESPONSE_ES9)

/* EUICC_CONFIGURED_ADDRESSES_REQUEST */
ASN1_SEQUENCE(EUICC_CONFIGURED_ADDRESSES_REQUEST) = {
    /* Empty sequence */
} ASN1_SEQUENCE_END(EUICC_CONFIGURED_ADDRESSES_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_CONFIGURED_ADDRESSES_REQUEST)

/* EUICC_CONFIGURED_ADDRESSES_RESPONSE */
ASN1_SEQUENCE(EUICC_CONFIGURED_ADDRESSES_RESPONSE) = {
    ASN1_OPT(EUICC_CONFIGURED_ADDRESSES_RESPONSE, defaultDpAddress, ASN1_UTF8STRING),
    ASN1_SIMPLE(EUICC_CONFIGURED_ADDRESSES_RESPONSE, rootDsAddress, ASN1_UTF8STRING)
} ASN1_SEQUENCE_END(EUICC_CONFIGURED_ADDRESSES_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(EUICC_CONFIGURED_ADDRESSES_RESPONSE)

/* ISDR_PROPRIETARY_APPLICATION_TEMPLATE */
ASN1_SEQUENCE(ISDR_PROPRIETARY_APPLICATION_TEMPLATE) = {
    ASN1_EXP(ISDR_PROPRIETARY_APPLICATION_TEMPLATE, svn, VersionType, 2),
    ASN1_OPT(ISDR_PROPRIETARY_APPLICATION_TEMPLATE, lpaeSupport, ASN1_BIT_STRING)
} ASN1_SEQUENCE_END(ISDR_PROPRIETARY_APPLICATION_TEMPLATE)
IMPLEMENT_ASN1_FUNCTIONS(ISDR_PROPRIETARY_APPLICATION_TEMPLATE)

/* LPAE_ACTIVATION_REQUEST */
ASN1_SEQUENCE(LPAE_ACTIVATION_REQUEST) = {
    ASN1_SIMPLE(LPAE_ACTIVATION_REQUEST, lpaeOption, ASN1_BIT_STRING)
} ASN1_SEQUENCE_END(LPAE_ACTIVATION_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(LPAE_ACTIVATION_REQUEST)

/* LPAE_ACTIVATION_RESPONSE */
ASN1_SEQUENCE(LPAE_ACTIVATION_RESPONSE) = {
    ASN1_SIMPLE(LPAE_ACTIVATION_RESPONSE, lpaeActivationResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(LPAE_ACTIVATION_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(LPAE_ACTIVATION_RESPONSE)

/* SET_DEFAULT_DP_ADDRESS_REQUEST */
ASN1_SEQUENCE(SET_DEFAULT_DP_ADDRESS_REQUEST) = {
    ASN1_SIMPLE(SET_DEFAULT_DP_ADDRESS_REQUEST, defaultDpAddress, ASN1_UTF8STRING)
} ASN1_SEQUENCE_END(SET_DEFAULT_DP_ADDRESS_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(SET_DEFAULT_DP_ADDRESS_REQUEST)

/* SET_DEFAULT_DP_ADDRESS_RESPONSE */
ASN1_SEQUENCE(SET_DEFAULT_DP_ADDRESS_RESPONSE) = {
    ASN1_SIMPLE(SET_DEFAULT_DP_ADDRESS_RESPONSE, setDefaultDpAddressResult, ASN1_INTEGER)
} ASN1_SEQUENCE_END(SET_DEFAULT_DP_ADDRESS_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(SET_DEFAULT_DP_ADDRESS_RESPONSE)

/* EVENT_ENTRIES */
ASN1_SEQUENCE(EVENT_ENTRIES) = {
    ASN1_SIMPLE(EVENT_ENTRIES, eventId, ASN1_UTF8STRING),
    ASN1_SIMPLE(EVENT_ENTRIES, rspServerAddress, ASN1_UTF8STRING)
} ASN1_SEQUENCE_END(EVENT_ENTRIES)
IMPLEMENT_ASN1_FUNCTIONS(EVENT_ENTRIES)

/* AUTHENTICATE_CLIENT_OK_ES11 */
ASN1_SEQUENCE(AUTHENTICATE_CLIENT_OK_ES11) = {
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_OK_ES11, transactionId, TransactionId),
    ASN1_SEQUENCE_OF(AUTHENTICATE_CLIENT_OK_ES11, eventEntries, EVENT_ENTRIES)
} ASN1_SEQUENCE_END(AUTHENTICATE_CLIENT_OK_ES11)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_OK_ES11)

/* AUTHENTICATE_CLIENT_RESPONSE_ES11 */
ASN1_CHOICE(AUTHENTICATE_CLIENT_RESPONSE_ES11) = {
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_RESPONSE_ES11, value.authenticateClientOk, AUTHENTICATE_CLIENT_OK_ES11),
    ASN1_SIMPLE(AUTHENTICATE_CLIENT_RESPONSE_ES11, value.authenticateClientError, ASN1_INTEGER)
} ASN1_CHOICE_END(AUTHENTICATE_CLIENT_RESPONSE_ES11)
IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_RESPONSE_ES11)

/* REMOTE_PROFILE_PROVISIONING_REQUEST */
ASN1_CHOICE(REMOTE_PROFILE_PROVISIONING_REQUEST) = {
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_REQUEST, value.initiateAuthenticationRequest, INITIATE_AUTHENTICATION_REQUEST, 57),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_REQUEST, value.authenticateClientRequest, AUTHENTICATE_CLIENT_REQUEST, 59),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_REQUEST, value.getBoundProfilePackageRequest, GET_BOUND_PROFILE_PACKAGE_REQUEST, 58),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_REQUEST, value.cancelSessionRequestEs9, CANCEL_SESSION_REQUEST_ES9, 65),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_REQUEST, value.handleNotification, HANDLE_NOTIFICATION, 61)
} ASN1_CHOICE_END(REMOTE_PROFILE_PROVISIONING_REQUEST)
IMPLEMENT_ASN1_FUNCTIONS(REMOTE_PROFILE_PROVISIONING_REQUEST)

/* REMOTE_PROFILE_PROVISIONING_RESPONSE */
ASN1_CHOICE(REMOTE_PROFILE_PROVISIONING_RESPONSE) = {
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_RESPONSE, value.initiateAuthenticationResponse, INITIATE_AUTHENTICATION_RESPONSE, 57),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_RESPONSE, value.authenticateClientResponseEs9, AUTHENTICATE_CLIENT_RESPONSE_ES9, 59),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_RESPONSE, value.getBoundProfilePackageResponse, GET_BOUND_PROFILE_PACKAGE_RESPONSE, 58),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_RESPONSE, value.cancelSessionResponseEs9, CANCEL_SESSION_RESPONSE_ES9, 65),
    ASN1_EXP(REMOTE_PROFILE_PROVISIONING_RESPONSE, value.authenticateClientResponseEs11, AUTHENTICATE_CLIENT_RESPONSE_ES11, 64)
} ASN1_CHOICE_END(REMOTE_PROFILE_PROVISIONING_RESPONSE)
IMPLEMENT_ASN1_FUNCTIONS(REMOTE_PROFILE_PROVISIONING_RESPONSE)

// /* If PRIVATE tag handling is needed, it would be implemented here with custom item templates */
// /* Example for handling PROFILE_INFO with PRIVATE 3 tag */

// /* Complete fixes for all ASN.1 structures that need proper context/private tags */

// // /* Fix EUICC_INFO1 - change from explicit to implicit tagging */
// // ASN1_ITEM_TEMPLATE(EUICC_INFO1) =
// //     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 32, EUICC_INFO1, EUICC_INFO1_INNER)
// // ASN1_ITEM_TEMPLATE_END(EUICC_INFO1)

// // /* Fix GET_EUICC_INFO1_REQUEST - change from explicit to implicit tagging */
// // ASN1_ITEM_TEMPLATE(GET_EUICC_INFO1_REQUEST) =
// //     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 32, GET_EUICC_INFO1_REQUEST, GET_EUICC_INFO1_REQUEST_INNER)
// // ASN1_ITEM_TEMPLATE_END(GET_EUICC_INFO1_REQUEST)

// /* Add missing context tag [34] for GET_EUICC_INFO2_REQUEST */
// ASN1_ITEM_TEMPLATE(GET_EUICC_INFO2_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 34, GET_EUICC_INFO2_REQUEST_TAGGED, GET_EUICC_INFO2_REQUEST)
// ASN1_ITEM_TEMPLATE_END(GET_EUICC_INFO2_REQUEST_TAGGED)

// /* Add missing context tag [34] for EUICC_INFO2 */
// ASN1_ITEM_TEMPLATE(EUICC_INFO2_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 34, EUICC_INFO2_TAGGED, EUICC_INFO2)
// ASN1_ITEM_TEMPLATE_END(EUICC_INFO2_TAGGED)

// /* Add missing context tag [45] for PROFILE_INFO_LIST_REQUEST */
// ASN1_ITEM_TEMPLATE(PROFILE_INFO_LIST_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 45, PROFILE_INFO_LIST_REQUEST_TAGGED, PROFILE_INFO_LIST_REQUEST)
// ASN1_ITEM_TEMPLATE_END(PROFILE_INFO_LIST_REQUEST_TAGGED)

// /* Add missing context tag [45] for PROFILE_INFO_LIST_RESPONSE */
// ASN1_ITEM_TEMPLATE(PROFILE_INFO_LIST_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 45, PROFILE_INFO_LIST_RESPONSE_TAGGED, PROFILE_INFO_LIST_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(PROFILE_INFO_LIST_RESPONSE_TAGGED)

// /* Add missing PRIVATE tag [3] for PROFILE_INFO */
// ASN1_ITEM_TEMPLATE(PROFILE_INFO_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_PRIVATE, 3, PROFILE_INFO_TAGGED, PROFILE_INFO)
// ASN1_ITEM_TEMPLATE_END(PROFILE_INFO_TAGGED)

// /* Add missing context tag [37] for STORE_METADATA_REQUEST */
// ASN1_ITEM_TEMPLATE(STORE_METADATA_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 37, STORE_METADATA_REQUEST_TAGGED, STORE_METADATA_REQUEST)
// ASN1_ITEM_TEMPLATE_END(STORE_METADATA_REQUEST_TAGGED)

// /* Add missing context tag [42] for UPDATE_METADATA_REQUEST */
// ASN1_ITEM_TEMPLATE(UPDATE_METADATA_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 42, UPDATE_METADATA_REQUEST_TAGGED, UPDATE_METADATA_REQUEST)
// ASN1_ITEM_TEMPLATE_END(UPDATE_METADATA_REQUEST_TAGGED)

// /* Add missing context tag [33] for PREPARE_DOWNLOAD_REQUEST */
// ASN1_ITEM_TEMPLATE(PREPARE_DOWNLOAD_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 33, PREPARE_DOWNLOAD_REQUEST_TAGGED, PREPARE_DOWNLOAD_REQUEST)
// ASN1_ITEM_TEMPLATE_END(PREPARE_DOWNLOAD_REQUEST_TAGGED)

// /* Add missing context tag [33] for PREPARE_DOWNLOAD_RESPONSE */
// ASN1_ITEM_TEMPLATE(PREPARE_DOWNLOAD_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 33, PREPARE_DOWNLOAD_RESPONSE_TAGGED, PREPARE_DOWNLOAD_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(PREPARE_DOWNLOAD_RESPONSE_TAGGED)

// /* Add missing context tag [56] for AUTHENTICATE_SERVER_REQUEST */
// ASN1_ITEM_TEMPLATE(AUTHENTICATE_SERVER_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 56, AUTHENTICATE_SERVER_REQUEST_TAGGED, AUTHENTICATE_SERVER_REQUEST)
// ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_SERVER_REQUEST_TAGGED)

// /* Add missing context tag [56] for AUTHENTICATE_SERVER_RESPONSE */
// ASN1_ITEM_TEMPLATE(AUTHENTICATE_SERVER_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 56, AUTHENTICATE_SERVER_RESPONSE_TAGGED, AUTHENTICATE_SERVER_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_SERVER_RESPONSE_TAGGED)

// /* Add missing context tag [65] for CANCEL_SESSION_REQUEST */
// ASN1_ITEM_TEMPLATE(CANCEL_SESSION_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 65, CANCEL_SESSION_REQUEST_TAGGED, CANCEL_SESSION_REQUEST)
// ASN1_ITEM_TEMPLATE_END(CANCEL_SESSION_REQUEST_TAGGED)

// /* Add missing context tag [65] for CANCEL_SESSION_RESPONSE */
// ASN1_ITEM_TEMPLATE(CANCEL_SESSION_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 65, CANCEL_SESSION_RESPONSE_TAGGED, CANCEL_SESSION_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(CANCEL_SESSION_RESPONSE_TAGGED)

// /* Add missing context tag [54] for BOUND_PROFILE_PACKAGE */
// ASN1_ITEM_TEMPLATE(BOUND_PROFILE_PACKAGE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 54, BOUND_PROFILE_PACKAGE_TAGGED, BOUND_PROFILE_PACKAGE)
// ASN1_ITEM_TEMPLATE_END(BOUND_PROFILE_PACKAGE_TAGGED)

// /* Add missing context tag [46] for GET_EUICC_CHALLENGE_REQUEST */
// ASN1_ITEM_TEMPLATE(GET_EUICC_CHALLENGE_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 46, GET_EUICC_CHALLENGE_REQUEST_TAGGED, GET_EUICC_CHALLENGE_REQUEST)
// ASN1_ITEM_TEMPLATE_END(GET_EUICC_CHALLENGE_REQUEST_TAGGED)

// /* Add missing context tag [46] for GET_EUICC_CHALLENGE_RESPONSE */
// ASN1_ITEM_TEMPLATE(GET_EUICC_CHALLENGE_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 46, GET_EUICC_CHALLENGE_RESPONSE_TAGGED, GET_EUICC_CHALLENGE_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(GET_EUICC_CHALLENGE_RESPONSE_TAGGED)

// /* Add missing context tag [55] for PROFILE_INSTALLATION_RESULT */
// ASN1_ITEM_TEMPLATE(PROFILE_INSTALLATION_RESULT_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 55, PROFILE_INSTALLATION_RESULT_TAGGED, PROFILE_INSTALLATION_RESULT)
// ASN1_ITEM_TEMPLATE_END(PROFILE_INSTALLATION_RESULT_TAGGED)

// /* Add missing context tag [39] for PROFILE_INSTALLATION_RESULT_DATA */
// ASN1_ITEM_TEMPLATE(PROFILE_INSTALLATION_RESULT_DATA_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 39, PROFILE_INSTALLATION_RESULT_DATA_TAGGED, PROFILE_INSTALLATION_RESULT_DATA)
// ASN1_ITEM_TEMPLATE_END(PROFILE_INSTALLATION_RESULT_DATA_TAGGED)

// /* Add missing context tag [40] for LIST_NOTIFICATION_REQUEST */
// ASN1_ITEM_TEMPLATE(LIST_NOTIFICATION_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 40, LIST_NOTIFICATION_REQUEST_TAGGED, LIST_NOTIFICATION_REQUEST)
// ASN1_ITEM_TEMPLATE_END(LIST_NOTIFICATION_REQUEST_TAGGED)

// /* Add missing context tag [40] for LIST_NOTIFICATION_RESPONSE */
// ASN1_ITEM_TEMPLATE(LIST_NOTIFICATION_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 40, LIST_NOTIFICATION_RESPONSE_TAGGED, LIST_NOTIFICATION_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(LIST_NOTIFICATION_RESPONSE_TAGGED)

// /* Add missing context tag [47] for NOTIFICATION_METADATA */
// ASN1_ITEM_TEMPLATE(NOTIFICATION_METADATA_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 47, NOTIFICATION_METADATA_TAGGED, NOTIFICATION_METADATA)
// ASN1_ITEM_TEMPLATE_END(NOTIFICATION_METADATA_TAGGED)

// /* Add missing context tag [41] for SET_NICKNAME_REQUEST */
// ASN1_ITEM_TEMPLATE(SET_NICKNAME_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 41, SET_NICKNAME_REQUEST_TAGGED, SET_NICKNAME_REQUEST)
// ASN1_ITEM_TEMPLATE_END(SET_NICKNAME_REQUEST_TAGGED)

// /* Add missing context tag [41] for SET_NICKNAME_RESPONSE */
// ASN1_ITEM_TEMPLATE(SET_NICKNAME_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 41, SET_NICKNAME_RESPONSE_TAGGED, SET_NICKNAME_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(SET_NICKNAME_RESPONSE_TAGGED)

// /* Add missing context tag [35] for INITIALISE_SECURE_CHANNEL_REQUEST */
// ASN1_ITEM_TEMPLATE(INITIALISE_SECURE_CHANNEL_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 35, INITIALISE_SECURE_CHANNEL_REQUEST_TAGGED, INITIALISE_SECURE_CHANNEL_REQUEST)
// ASN1_ITEM_TEMPLATE_END(INITIALISE_SECURE_CHANNEL_REQUEST_TAGGED)

// /* Add missing context tag [36] for CONFIGURE_ISDP_REQUEST */
// ASN1_ITEM_TEMPLATE(CONFIGURE_ISDP_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 36, CONFIGURE_ISDP_REQUEST_TAGGED, CONFIGURE_ISDP_REQUEST)
// ASN1_ITEM_TEMPLATE_END(CONFIGURE_ISDP_REQUEST_TAGGED)

// /* Add missing context tag [38] for REPLACE_SESSION_KEYS_REQUEST */
// ASN1_ITEM_TEMPLATE(REPLACE_SESSION_KEYS_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 38, REPLACE_SESSION_KEYS_REQUEST_TAGGED, REPLACE_SESSION_KEYS_REQUEST)
// ASN1_ITEM_TEMPLATE_END(REPLACE_SESSION_KEYS_REQUEST_TAGGED)

// /* Add missing context tag [43] for RETRIEVE_NOTIFICATIONS_LIST_REQUEST */
// /* First need to add the missing inner structure definition */
// ASN1_CHOICE(RETRIEVE_NOTIFICATIONS_LIST_REQUEST) = {
//     ASN1_EXP(RETRIEVE_NOTIFICATIONS_LIST_REQUEST, searchCriteria.seqNumber, ASN1_INTEGER, 0),
//     ASN1_EXP(RETRIEVE_NOTIFICATIONS_LIST_REQUEST, searchCriteria.profileManagementOperation, ASN1_BIT_STRING, 1)
// } ASN1_CHOICE_END(RETRIEVE_NOTIFICATIONS_LIST_REQUEST)

// ASN1_ITEM_TEMPLATE(RETRIEVE_NOTIFICATIONS_LIST_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 43, RETRIEVE_NOTIFICATIONS_LIST_REQUEST_TAGGED, RETRIEVE_NOTIFICATIONS_LIST_REQUEST)
// ASN1_ITEM_TEMPLATE_END(RETRIEVE_NOTIFICATIONS_LIST_REQUEST_TAGGED)

// /* Add missing context tag [43] for RETRIEVE_NOTIFICATIONS_LIST_RESPONSE */
// /* Note: This was commented out in the original - needs to be uncommented */
// ASN1_CHOICE(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE) = {
//     ASN1_SEQUENCE_OF(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE, value.notificationList, PENDING_NOTIFICATION),
//     ASN1_SIMPLE(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE, value.notificationsListResultError, ASN1_INTEGER)
// } ASN1_CHOICE_END(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE)

// ASN1_ITEM_TEMPLATE(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 43, RETRIEVE_NOTIFICATIONS_LIST_RESPONSE_TAGGED, RETRIEVE_NOTIFICATIONS_LIST_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE_TAGGED)

// /* Add missing context tag [48] for NOTIFICATION_SENT_REQUEST */
// ASN1_ITEM_TEMPLATE(NOTIFICATION_SENT_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 48, NOTIFICATION_SENT_REQUEST_TAGGED, NOTIFICATION_SENT_REQUEST)
// ASN1_ITEM_TEMPLATE_END(NOTIFICATION_SENT_REQUEST_TAGGED)

// /* Add missing context tag [48] for NOTIFICATION_SENT_RESPONSE */
// ASN1_ITEM_TEMPLATE(NOTIFICATION_SENT_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 48, NOTIFICATION_SENT_RESPONSE_TAGGED, NOTIFICATION_SENT_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(NOTIFICATION_SENT_RESPONSE_TAGGED)

// /* Add missing ENABLE/DISABLE/DELETE profile request/response tags [49], [50], [51] */
// /* First need to define the missing inner structures */
// ASN1_CHOICE(ENABLE_PROFILE_REQUEST) = {
//     ASN1_IMP(ENABLE_PROFILE_REQUEST, profileIdentifier.isdpAid, ASN1_OCTET_STRING, 15),
//     ASN1_SIMPLE(ENABLE_PROFILE_REQUEST, profileIdentifier.iccid, Iccid)
// } ASN1_CHOICE_END(ENABLE_PROFILE_REQUEST)

// ASN1_SEQUENCE(ENABLE_PROFILE_REQUEST_SEQ) = {
//     ASN1_SIMPLE(ENABLE_PROFILE_REQUEST_SEQ, profileIdentifier, ENABLE_PROFILE_REQUEST),
//     ASN1_SIMPLE(ENABLE_PROFILE_REQUEST_SEQ, refreshFlag, ASN1_BOOLEAN)
// } ASN1_SEQUENCE_END(ENABLE_PROFILE_REQUEST_SEQ)

// ASN1_ITEM_TEMPLATE(ENABLE_PROFILE_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 49, ENABLE_PROFILE_REQUEST_TAGGED, ENABLE_PROFILE_REQUEST_SEQ)
// ASN1_ITEM_TEMPLATE_END(ENABLE_PROFILE_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(ENABLE_PROFILE_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 49, ENABLE_PROFILE_RESPONSE_TAGGED, ENABLE_PROFILE_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(ENABLE_PROFILE_RESPONSE_TAGGED)

// /* Similar for DISABLE_PROFILE_REQUEST/RESPONSE [50] */
// ASN1_CHOICE(DISABLE_PROFILE_REQUEST) = {
//     ASN1_IMP(DISABLE_PROFILE_REQUEST, profileIdentifier.isdpAid, ASN1_OCTET_STRING, 15),
//     ASN1_SIMPLE(DISABLE_PROFILE_REQUEST, profileIdentifier.iccid, Iccid)
// } ASN1_CHOICE_END(DISABLE_PROFILE_REQUEST)

// ASN1_SEQUENCE(DISABLE_PROFILE_REQUEST_SEQ) = {
//     ASN1_SIMPLE(DISABLE_PROFILE_REQUEST_SEQ, profileIdentifier, DISABLE_PROFILE_REQUEST),
//     ASN1_SIMPLE(DISABLE_PROFILE_REQUEST_SEQ, refreshFlag, ASN1_BOOLEAN)
// } ASN1_SEQUENCE_END(DISABLE_PROFILE_REQUEST_SEQ)

// ASN1_ITEM_TEMPLATE(DISABLE_PROFILE_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 50, DISABLE_PROFILE_REQUEST_TAGGED, DISABLE_PROFILE_REQUEST_SEQ)
// ASN1_ITEM_TEMPLATE_END(DISABLE_PROFILE_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(DISABLE_PROFILE_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 50, DISABLE_PROFILE_RESPONSE_TAGGED, DISABLE_PROFILE_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(DISABLE_PROFILE_RESPONSE_TAGGED)

// /* DELETE_PROFILE_REQUEST/RESPONSE [51] */
// ASN1_ITEM_TEMPLATE(DELETE_PROFILE_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 51, DELETE_PROFILE_REQUEST_TAGGED, DELETE_PROFILE_REQUEST)
// ASN1_ITEM_TEMPLATE_END(DELETE_PROFILE_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(DELETE_PROFILE_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 51, DELETE_PROFILE_RESPONSE_TAGGED, DELETE_PROFILE_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(DELETE_PROFILE_RESPONSE_TAGGED)

// /* Continue with remaining structures... */

// /* EUICC_MEMORY_RESET_REQUEST/RESPONSE [52] */
// ASN1_ITEM_TEMPLATE(EUICC_MEMORY_RESET_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 52, EUICC_MEMORY_RESET_REQUEST_TAGGED, EUICC_MEMORY_RESET_REQUEST)
// ASN1_ITEM_TEMPLATE_END(EUICC_MEMORY_RESET_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(EUICC_MEMORY_RESET_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 52, EUICC_MEMORY_RESET_RESPONSE_TAGGED, EUICC_MEMORY_RESET_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(EUICC_MEMORY_RESET_RESPONSE_TAGGED)

// /* GET_EUICC_DATA_REQUEST/RESPONSE [62] */
// ASN1_ITEM_TEMPLATE(GET_EUICC_DATA_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 62, GET_EUICC_DATA_REQUEST_TAGGED, GET_EUICC_DATA_REQUEST)
// ASN1_ITEM_TEMPLATE_END(GET_EUICC_DATA_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(GET_EUICC_DATA_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 62, GET_EUICC_DATA_RESPONSE_TAGGED, GET_EUICC_DATA_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(GET_EUICC_DATA_RESPONSE_TAGGED)

// /* GET_RAT_REQUEST/RESPONSE [67] */
// ASN1_ITEM_TEMPLATE(GET_RAT_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 67, GET_RAT_REQUEST_TAGGED, GET_RAT_REQUEST)
// ASN1_ITEM_TEMPLATE_END(GET_RAT_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(GET_RAT_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 67, GET_RAT_RESPONSE_TAGGED, GET_RAT_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(GET_RAT_RESPONSE_TAGGED)

// /* LOAD_CRL_REQUEST/RESPONSE [53] */
// ASN1_ITEM_TEMPLATE(LOAD_CRL_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 53, LOAD_CRL_REQUEST_TAGGED, LOAD_CRL_REQUEST)
// ASN1_ITEM_TEMPLATE_END(LOAD_CRL_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(LOAD_CRL_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 53, LOAD_CRL_RESPONSE_TAGGED, LOAD_CRL_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(LOAD_CRL_RESPONSE_TAGGED)

// /* ES9+ Interface structures */

// /* REMOTE_PROFILE_PROVISIONING_REQUEST/RESPONSE [2] */
// ASN1_ITEM_TEMPLATE(REMOTE_PROFILE_PROVISIONING_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 2, REMOTE_PROFILE_PROVISIONING_REQUEST_TAGGED, REMOTE_PROFILE_PROVISIONING_REQUEST)
// ASN1_ITEM_TEMPLATE_END(REMOTE_PROFILE_PROVISIONING_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(REMOTE_PROFILE_PROVISIONING_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 2, REMOTE_PROFILE_PROVISIONING_RESPONSE_TAGGED, REMOTE_PROFILE_PROVISIONING_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(REMOTE_PROFILE_PROVISIONING_RESPONSE_TAGGED)

// /* INITIATE_AUTHENTICATION_REQUEST/RESPONSE [57] */
// ASN1_ITEM_TEMPLATE(INITIATE_AUTHENTICATION_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 57, INITIATE_AUTHENTICATION_REQUEST_TAGGED, INITIATE_AUTHENTICATION_REQUEST)
// ASN1_ITEM_TEMPLATE_END(INITIATE_AUTHENTICATION_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(INITIATE_AUTHENTICATION_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 57, INITIATE_AUTHENTICATION_RESPONSE_TAGGED, INITIATE_AUTHENTICATION_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(INITIATE_AUTHENTICATION_RESPONSE_TAGGED)

// /* AUTHENTICATE_CLIENT_REQUEST/RESPONSE [59] */
// ASN1_ITEM_TEMPLATE(AUTHENTICATE_CLIENT_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 59, AUTHENTICATE_CLIENT_REQUEST_TAGGED, AUTHENTICATE_CLIENT_REQUEST)
// ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_CLIENT_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(AUTHENTICATE_CLIENT_RESPONSE_ES9_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 59, AUTHENTICATE_CLIENT_RESPONSE_ES9_TAGGED, AUTHENTICATE_CLIENT_RESPONSE_ES9)
// ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_CLIENT_RESPONSE_ES9_TAGGED)

// /* GET_BOUND_PROFILE_PACKAGE_REQUEST/RESPONSE [58] */
// ASN1_ITEM_TEMPLATE(GET_BOUND_PROFILE_PACKAGE_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 58, GET_BOUND_PROFILE_PACKAGE_REQUEST_TAGGED, GET_BOUND_PROFILE_PACKAGE_REQUEST)
// ASN1_ITEM_TEMPLATE_END(GET_BOUND_PROFILE_PACKAGE_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(GET_BOUND_PROFILE_PACKAGE_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 58, GET_BOUND_PROFILE_PACKAGE_RESPONSE_TAGGED, GET_BOUND_PROFILE_PACKAGE_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(GET_BOUND_PROFILE_PACKAGE_RESPONSE_TAGGED)

// /* HANDLE_NOTIFICATION [61] */
// ASN1_ITEM_TEMPLATE(HANDLE_NOTIFICATION_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 61, HANDLE_NOTIFICATION_TAGGED, HANDLE_NOTIFICATION)
// ASN1_ITEM_TEMPLATE_END(HANDLE_NOTIFICATION_TAGGED)

// /* CANCEL_SESSION_REQUEST_ES9/RESPONSE_ES9 [65] */
// ASN1_ITEM_TEMPLATE(CANCEL_SESSION_REQUEST_ES9_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 65, CANCEL_SESSION_REQUEST_ES9_TAGGED, CANCEL_SESSION_REQUEST_ES9)
// ASN1_ITEM_TEMPLATE_END(CANCEL_SESSION_REQUEST_ES9_TAGGED)

// ASN1_ITEM_TEMPLATE(CANCEL_SESSION_RESPONSE_ES9_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 65, CANCEL_SESSION_RESPONSE_ES9_TAGGED, CANCEL_SESSION_RESPONSE_ES9)
// ASN1_ITEM_TEMPLATE_END(CANCEL_SESSION_RESPONSE_ES9_TAGGED)

// /* EUICC_CONFIGURED_ADDRESSES_REQUEST/RESPONSE [60] */
// ASN1_ITEM_TEMPLATE(EUICC_CONFIGURED_ADDRESSES_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 60, EUICC_CONFIGURED_ADDRESSES_REQUEST_TAGGED, EUICC_CONFIGURED_ADDRESSES_REQUEST)
// ASN1_ITEM_TEMPLATE_END(EUICC_CONFIGURED_ADDRESSES_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(EUICC_CONFIGURED_ADDRESSES_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 60, EUICC_CONFIGURED_ADDRESSES_RESPONSE_TAGGED, EUICC_CONFIGURED_ADDRESSES_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(EUICC_CONFIGURED_ADDRESSES_RESPONSE_TAGGED)

// /* ISDR_PROPRIETARY_APPLICATION_TEMPLATE [PRIVATE 0] */
// ASN1_ITEM_TEMPLATE(ISDR_PROPRIETARY_APPLICATION_TEMPLATE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_PRIVATE, 0, ISDR_PROPRIETARY_APPLICATION_TEMPLATE_TAGGED, ISDR_PROPRIETARY_APPLICATION_TEMPLATE)
// ASN1_ITEM_TEMPLATE_END(ISDR_PROPRIETARY_APPLICATION_TEMPLATE_TAGGED)

// /* LPAE_ACTIVATION_REQUEST/RESPONSE [66] */
// ASN1_ITEM_TEMPLATE(LPAE_ACTIVATION_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 66, LPAE_ACTIVATION_REQUEST_TAGGED, LPAE_ACTIVATION_REQUEST)
// ASN1_ITEM_TEMPLATE_END(LPAE_ACTIVATION_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(LPAE_ACTIVATION_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 66, LPAE_ACTIVATION_RESPONSE_TAGGED, LPAE_ACTIVATION_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(LPAE_ACTIVATION_RESPONSE_TAGGED)

// /* SET_DEFAULT_DP_ADDRESS_REQUEST/RESPONSE [63] */
// ASN1_ITEM_TEMPLATE(SET_DEFAULT_DP_ADDRESS_REQUEST_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 63, SET_DEFAULT_DP_ADDRESS_REQUEST_TAGGED, SET_DEFAULT_DP_ADDRESS_REQUEST)
// ASN1_ITEM_TEMPLATE_END(SET_DEFAULT_DP_ADDRESS_REQUEST_TAGGED)

// ASN1_ITEM_TEMPLATE(SET_DEFAULT_DP_ADDRESS_RESPONSE_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 63, SET_DEFAULT_DP_ADDRESS_RESPONSE_TAGGED, SET_DEFAULT_DP_ADDRESS_RESPONSE)
// ASN1_ITEM_TEMPLATE_END(SET_DEFAULT_DP_ADDRESS_RESPONSE_TAGGED)

// /* AUTHENTICATE_CLIENT_RESPONSE_ES11 [64] */
// ASN1_ITEM_TEMPLATE(AUTHENTICATE_CLIENT_RESPONSE_ES11_TAGGED) =
//     ASN1_EX_TEMPLATE_TYPE(ASN1_TFLG_IMPTAG | ASN1_TFLG_CONTEXT, 64, AUTHENTICATE_CLIENT_RESPONSE_ES11_TAGGED, AUTHENTICATE_CLIENT_RESPONSE_ES11)
// ASN1_ITEM_TEMPLATE_END(AUTHENTICATE_CLIENT_RESPONSE_ES11_TAGGED)

// /* Don't forget to implement ASN1 functions for all the new tagged types */
// // IMPLEMENT_ASN1_FUNCTIONS(EUICC_INFO2_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_INFO2_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_LIST_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INFO_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(STORE_METADATA_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(UPDATE_METADATA_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PREPARE_DOWNLOAD_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_SERVER_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_SERVER_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(BOUND_PROFILE_PACKAGE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_CHALLENGE_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_CHALLENGE_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INSTALLATION_RESULT_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(PROFILE_INSTALLATION_RESULT_DATA_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LIST_NOTIFICATION_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LIST_NOTIFICATION_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_METADATA_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(SET_NICKNAME_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(SET_NICKNAME_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(INITIALISE_SECURE_CHANNEL_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(CONFIGURE_ISDP_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(REPLACE_SESSION_KEYS_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(RETRIEVE_NOTIFICATIONS_LIST_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_SENT_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(NOTIFICATION_SENT_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(ENABLE_PROFILE_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(ENABLE_PROFILE_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(DISABLE_PROFILE_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(DISABLE_PROFILE_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(DELETE_PROFILE_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(DELETE_PROFILE_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(EUICC_MEMORY_RESET_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(EUICC_MEMORY_RESET_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_DATA_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_EUICC_DATA_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_RAT_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_RAT_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LOAD_CRL_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LOAD_CRL_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(REMOTE_PROFILE_PROVISIONING_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(REMOTE_PROFILE_PROVISIONING_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(INITIATE_AUTHENTICATION_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(INITIATE_AUTHENTICATION_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_RESPONSE_ES9_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(GET_BOUND_PROFILE_PACKAGE_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(HANDLE_NOTIFICATION_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_REQUEST_ES9_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(CANCEL_SESSION_RESPONSE_ES9_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(EUICC_CONFIGURED_ADDRESSES_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(EUICC_CONFIGURED_ADDRESSES_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(ISDR_PROPRIETARY_APPLICATION_TEMPLATE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LPAE_ACTIVATION_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(LPAE_ACTIVATION_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(SET_DEFAULT_DP_ADDRESS_REQUEST_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(SET_DEFAULT_DP_ADDRESS_RESPONSE_TAGGED)
// IMPLEMENT_ASN1_FUNCTIONS(AUTHENTICATE_CLIENT_RESPONSE_ES11_TAGGED)

// /* Also implement the missing inner structures */
// IMPLEMENT_ASN1_FUNCTIONS(RETRIEVE_NOTIFICATIONS_LIST_REQUEST)
// IMPLEMENT_ASN1_FUNCTIONS(RETRIEVE_NOTIFICATIONS_LIST_RESPONSE)
// IMPLEMENT_ASN1_FUNCTIONS(ENABLE_PROFILE_REQUEST)
// IMPLEMENT_ASN1_FUNCTIONS(ENABLE_PROFILE_REQUEST_SEQ)
// IMPLEMENT_ASN1_FUNCTIONS(DISABLE_PROFILE_REQUEST)
// IMPLEMENT_ASN1_FUNCTIONS(DISABLE_PROFILE_REQUEST_SEQ)